### ISSUE TITLE
Gray modified gutter is hard to read

### ISSUE THREAD

**Issue by WardsParadox** [davidleininger/cobaltnext-vscode#11]
The gray `editorGutter.modifiedBackground` is rather hard to see unless you are looking straight on the screen. Would it be beneficial to use the same color as the orange for the text for the modified Gutter? `#fac863` is the color I see the most for the text.

Suggestion visuallized:

Before:
![image](https://user-images.githubusercontent.com/8117192/58570737-b67b1100-81f5-11e9-9bc3-4c814faedb4a.png)

After:
![image](https://user-images.githubusercontent.com/8117192/58570671-a6fbc800-81f5-11e9-8b0f-229c19cf4991.png)

**Comment by davidleininger** [comment]
I totally agree. This one just slipped away from me. This also made me realize that I don't match that color from the `editorOverviewRuler.modifiedForeground`. I'll sync those two up and push that update tonight. 

I might go with `#5a9bcf` since the yellow (`#fac863`) is already used for `editorOverviewRuler.warningContentForeground`.

**Comment by davidleininger** [comment]
Went with `#fac863aa`. Also made some updates to `editorOverviewRuler`. Thanks for pointing this out!

**Comment by noseglid** [comment]
Thank you so much for this! Literally the only thing I've been bothered with using this theme, and it was so minor I didn't even think of it.

Now it's perfect!
